pipeline {
    agent any

    tools {
        // These tool names should match the ones configured in your Jenkins Global Tool Configuration
        maven 'maven-3'
        jdk   'jdk-17'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from the repository (handled automatically by Jenkins for SCM jobs)
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                // Run Maven tests
                sh 'mvn clean test'
            }
            post {
                always {
                    // Archive TestNG results if any are generated by Surefire
                    junit testResults: "target/surefire-reports/*.xml", allowEmptyResults: true
                }
            }
        }

        stage('Allure Reporting') {
            steps {
                script {
                    // Generate Allure report. This requires the Allure Jenkins Plugin.
                    allure includeProperties: false, jdk: '', results: [[path: "allure-results"]]
                }
            }
        }
    }

    post {
        always {
            // Clean up workspace after build
            cleanWs()
        }
        success {
            echo 'Build and Tests completed successfully!'
        }
        failure {
            echo 'Build or Tests failed. Please check the logs.'
        }
    }
}
